package com.myhistory.datos.tablas;
// Generated 11/06/2014 09:46:48 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="ADMINISTRADOR"
    ,schema="dbo"
    ,catalog="MY_HISTORY"
)
public class Administrador  implements java.io.Serializable {


     private int pkFkCuenta;
     private Cuenta cuenta;
     private String nombre;
     private String apellido;
     private Date fechaNacimiento;

    public Administrador() {
    }

    public Administrador(Cuenta cuenta, String nombre, String apellido, Date fechaNacimiento) {
       this.cuenta = cuenta;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="cuenta"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="PK_FK_Cuenta", unique=true, nullable=false)
    public int getPkFkCuenta() {
        return this.pkFkCuenta;
    }
    
    public void setPkFkCuenta(int pkFkCuenta) {
        this.pkFkCuenta = pkFkCuenta;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }

    
    @Column(name="Nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", nullable=false, length=30)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_Nacimiento", nullable=false, length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }




}


