package com.myhistory.datos.tablas;
// Generated 11/06/2014 09:46:48 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name="CUENTA"
    ,schema="dbo"
    ,catalog="MY_HISTORY"
)
public class Cuenta  implements java.io.Serializable {


     private int pkCuenta;
     private String nombreUsuario;
     private String contrasena;
     private Date fechaInscripcion;
     private boolean estado;
     private Administrador administrador;

    public Cuenta() {
    }

	
    public Cuenta(int pkCuenta, String nombreUsuario, String contrasena, Date fechaInscripcion, boolean estado) {
        this.pkCuenta = pkCuenta;
        this.nombreUsuario = nombreUsuario;
        this.contrasena = contrasena;
        this.fechaInscripcion = fechaInscripcion;
        this.estado = estado;
    }
    public Cuenta(int pkCuenta, String nombreUsuario, String contrasena, Date fechaInscripcion, boolean estado, Administrador administrador) {
       this.pkCuenta = pkCuenta;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.fechaInscripcion = fechaInscripcion;
       this.estado = estado;
       this.administrador = administrador;
    }
   
     @Id 

    
    @Column(name="PK_Cuenta", unique=true, nullable=false)
    public int getPkCuenta() {
        return this.pkCuenta;
    }
    
    public void setPkCuenta(int pkCuenta) {
        this.pkCuenta = pkCuenta;
    }

    
    @Column(name="Nombre_Usuario", nullable=false, length=12)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="Contrasena", nullable=false, length=8)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_Inscripcion", nullable=false, length=10)
    public Date getFechaInscripcion() {
        return this.fechaInscripcion;
    }
    
    public void setFechaInscripcion(Date fechaInscripcion) {
        this.fechaInscripcion = fechaInscripcion;
    }

    
    @Column(name="Estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="cuenta")
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }




}


