package com.myhistory.datos.tablas;
// Generated 11/06/2014 09:46:48 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Posicion generated by hbm2java
 */
@Entity
@Table(name="POSICION"
    ,schema="dbo"
    ,catalog="MY_HISTORY"
)
public class Posicion  implements java.io.Serializable {


     private int pkPosicion;
     private String nombrePosicion;
     private Set<Jugador> jugadors = new HashSet<Jugador>(0);

    public Posicion() {
    }

	
    public Posicion(int pkPosicion, String nombrePosicion) {
        this.pkPosicion = pkPosicion;
        this.nombrePosicion = nombrePosicion;
    }
    public Posicion(int pkPosicion, String nombrePosicion, Set<Jugador> jugadors) {
       this.pkPosicion = pkPosicion;
       this.nombrePosicion = nombrePosicion;
       this.jugadors = jugadors;
    }
   
     @Id 

    
    @Column(name="PK_Posicion", unique=true, nullable=false)
    public int getPkPosicion() {
        return this.pkPosicion;
    }
    
    public void setPkPosicion(int pkPosicion) {
        this.pkPosicion = pkPosicion;
    }

    
    @Column(name="Nombre_Posicion", nullable=false, length=45)
    public String getNombrePosicion() {
        return this.nombrePosicion;
    }
    
    public void setNombrePosicion(String nombrePosicion) {
        this.nombrePosicion = nombrePosicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="posicion")
    public Set<Jugador> getJugadors() {
        return this.jugadors;
    }
    
    public void setJugadors(Set<Jugador> jugadors) {
        this.jugadors = jugadors;
    }




}


