//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoccer.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCION
    {
        public ACCION()
        {
            this.COMENTARIO_ESTADISTICO = new HashSet<COMENTARIO_ESTADISTICO>();
        }
    
        public int PK_Accion { get; set; }
        public string Nombre_Accion { get; set; }
    
        public virtual ICollection<COMENTARIO_ESTADISTICO> COMENTARIO_ESTADISTICO { get; set; }
    }
}
