//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoccer.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMENTARIO
    {
        public int PK_Comentario { get; set; }
        public string Comentario1 { get; set; }
        public int Tiempo { get; set; }
        public int FK_Partido_Registrado { get; set; }
        public int FK_Narrador { get; set; }
        public int FK_Fanatico { get; set; }
    
        public virtual NARRADOR NARRADOR { get; set; }
        public virtual FANATICO FANATICO { get; set; }
    }
}
