//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoccer.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMENTARIO_ESTADISTICO
    {
        public int PK_Comentario_Estadistico { get; set; }
        public int Tiempo { get; set; }
        public int FK_Jugador_1 { get; set; }
        public int FK_Jugador_2 { get; set; }
        public int FK_Equipo { get; set; }
        public int FK_Partido { get; set; }
        public int FK_Accion { get; set; }
    
        public virtual ACCION ACCION { get; set; }
        public virtual EQUIPO EQUIPO { get; set; }
    }
}
