//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoccer.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        public int PK_Cuenta { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Contrasena { get; set; }
        public System.DateTime Fecha_Inscripcion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
    }
}
