//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoccer.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO
    {
        public EQUIPO()
        {
            this.JUGADOR = new HashSet<JUGADOR>();
            this.PERFIL_ESTADISTICO = new HashSet<PERFIL_ESTADISTICO>();
        }
    
        public int PK_Equipo { get; set; }
        public string Nombre { get; set; }
        public bool De_Selecion { get; set; }
        public int FK_Pais { get; set; }
    
        public virtual PAIS PAIS { get; set; }
        public virtual ICollection<JUGADOR> JUGADOR { get; set; }
        public virtual ICollection<PERFIL_ESTADISTICO> PERFIL_ESTADISTICO { get; set; }
    }
}
