//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoccer.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class NARRADOR
    {
        public NARRADOR()
        {
            this.COMENTARIO = new HashSet<COMENTARIO>();
            this.PARTIDO_REGISTRADO = new HashSet<PARTIDO_REGISTRADO>();
        }
    
        public int PK_FK_Narrador { get; set; }
        public int Genero { get; set; }
        public string Foto { get; set; }
        public int Anos_Experiencia { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<COMENTARIO> COMENTARIO { get; set; }
        public virtual ICollection<PARTIDO_REGISTRADO> PARTIDO_REGISTRADO { get; set; }
    }
}
