//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoccer.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIS
    {
        public PAIS()
        {
            this.EQUIPO = new HashSet<EQUIPO>();
            this.JUGADOR = new HashSet<JUGADOR>();
        }
    
        public int PK_Pais { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<EQUIPO> EQUIPO { get; set; }
        public virtual ICollection<JUGADOR> JUGADOR { get; set; }
    }
}
