//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoccer.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TORNEO
    {
        public TORNEO()
        {
            this.PERFIL_ESTADISTICO = new HashSet<PERFIL_ESTADISTICO>();
        }
    
        public int PK_Torneo { get; set; }
        public string Nombre { get; set; }
        public int Cantidad_Jugadores { get; set; }
        public bool De_Seleccion { get; set; }
        public bool De_Copa { get; set; }
    
        public virtual ICollection<PERFIL_ESTADISTICO> PERFIL_ESTADISTICO { get; set; }
    }
}
