package com.myhistory.datos.tablas;
// Generated 16/06/2014 01:29:29 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jugador generated by hbm2java
 */
@Entity
@Table(name="JUGADOR"
    ,schema="dbo"
    ,catalog="MY_HISTORY"
)
public class Jugador  implements java.io.Serializable {


     private int pkPasaporteXfifa;
     private Pais pais;
     private Posicion posicion;
     private Equipo equipo;
     private String nombre;
     private Date fechaNacimiento;
     private int altura;
     private int peso;
     private boolean estado;
     private String foto;
     private Set<PerfilEstadistico> perfilEstadisticos = new HashSet<PerfilEstadistico>(0);

    public Jugador() {
    }

	
    public Jugador(int pkPasaporteXfifa, Pais pais, Posicion posicion, Equipo equipo, String nombre, Date fechaNacimiento, int altura, int peso, boolean estado) {
        this.pkPasaporteXfifa = pkPasaporteXfifa;
        this.pais = pais;
        this.posicion = posicion;
        this.equipo = equipo;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
        this.altura = altura;
        this.peso = peso;
        this.estado = estado;
    }
    public Jugador(int pkPasaporteXfifa, Pais pais, Posicion posicion, Equipo equipo, String nombre, Date fechaNacimiento, int altura, int peso, boolean estado, String foto, Set<PerfilEstadistico> perfilEstadisticos) {
       this.pkPasaporteXfifa = pkPasaporteXfifa;
       this.pais = pais;
       this.posicion = posicion;
       this.equipo = equipo;
       this.nombre = nombre;
       this.fechaNacimiento = fechaNacimiento;
       this.altura = altura;
       this.peso = peso;
       this.estado = estado;
       this.foto = foto;
       this.perfilEstadisticos = perfilEstadisticos;
    }
   
     @Id 

    
    @Column(name="PK_Pasaporte_XFIFA", unique=true, nullable=false)
    public int getPkPasaporteXfifa() {
        return this.pkPasaporteXfifa;
    }
    
    public void setPkPasaporteXfifa(int pkPasaporteXfifa) {
        this.pkPasaporteXfifa = pkPasaporteXfifa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_Pais", nullable=false)
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_Posicion", nullable=false)
    public Posicion getPosicion() {
        return this.posicion;
    }
    
    public void setPosicion(Posicion posicion) {
        this.posicion = posicion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_Equipo_Actual", nullable=false)
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }

    
    @Column(name="Nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_Nacimiento", nullable=false, length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="Altura", nullable=false)
    public int getAltura() {
        return this.altura;
    }
    
    public void setAltura(int altura) {
        this.altura = altura;
    }

    
    @Column(name="Peso", nullable=false)
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }

    
    @Column(name="Estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    
    @Column(name="Foto", length=50)
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jugador")
    public Set<PerfilEstadistico> getPerfilEstadisticos() {
        return this.perfilEstadisticos;
    }
    
    public void setPerfilEstadisticos(Set<PerfilEstadistico> perfilEstadisticos) {
        this.perfilEstadisticos = perfilEstadisticos;
    }




}


