package com.myhistory.datos.tablas;
// Generated 16/06/2014 01:29:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="PAIS"
    ,schema="dbo"
    ,catalog="MY_HISTORY"
)
public class Pais  implements java.io.Serializable {


     private int pkPais;
     private String nombre;
     private Set<Equipo> equipos = new HashSet<Equipo>(0);
     private Set<Jugador> jugadors = new HashSet<Jugador>(0);

    public Pais() {
    }

	
    public Pais(int pkPais, String nombre) {
        this.pkPais = pkPais;
        this.nombre = nombre;
    }
    public Pais(int pkPais, String nombre, Set<Equipo> equipos, Set<Jugador> jugadors) {
       this.pkPais = pkPais;
       this.nombre = nombre;
       this.equipos = equipos;
       this.jugadors = jugadors;
    }
   
     @Id 

    
    @Column(name="PK_Pais", unique=true, nullable=false)
    public int getPkPais() {
        return this.pkPais;
    }
    
    public void setPkPais(int pkPais) {
        this.pkPais = pkPais;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pais")
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pais")
    public Set<Jugador> getJugadors() {
        return this.jugadors;
    }
    
    public void setJugadors(Set<Jugador> jugadors) {
        this.jugadors = jugadors;
    }




}


