package com.myhistory.datos.tablas;
// Generated 16/06/2014 01:29:29 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfilEstadisticoId generated by hbm2java
 */
@Embeddable
public class PerfilEstadisticoId  implements java.io.Serializable {


     private int pkFkPasaporteXfifa;
     private int pkFkEquipo;
     private int pkFkTorneo;

    public PerfilEstadisticoId() {
    }

    public PerfilEstadisticoId(int pkFkPasaporteXfifa, int pkFkEquipo, int pkFkTorneo) {
       this.pkFkPasaporteXfifa = pkFkPasaporteXfifa;
       this.pkFkEquipo = pkFkEquipo;
       this.pkFkTorneo = pkFkTorneo;
    }
   


    @Column(name="PK_FK_Pasaporte_XFIFA", nullable=false)
    public int getPkFkPasaporteXfifa() {
        return this.pkFkPasaporteXfifa;
    }
    
    public void setPkFkPasaporteXfifa(int pkFkPasaporteXfifa) {
        this.pkFkPasaporteXfifa = pkFkPasaporteXfifa;
    }


    @Column(name="PK_FK_Equipo", nullable=false)
    public int getPkFkEquipo() {
        return this.pkFkEquipo;
    }
    
    public void setPkFkEquipo(int pkFkEquipo) {
        this.pkFkEquipo = pkFkEquipo;
    }


    @Column(name="PK_FK_Torneo", nullable=false)
    public int getPkFkTorneo() {
        return this.pkFkTorneo;
    }
    
    public void setPkFkTorneo(int pkFkTorneo) {
        this.pkFkTorneo = pkFkTorneo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PerfilEstadisticoId) ) return false;
		 PerfilEstadisticoId castOther = ( PerfilEstadisticoId ) other; 
         
		 return (this.getPkFkPasaporteXfifa()==castOther.getPkFkPasaporteXfifa())
 && (this.getPkFkEquipo()==castOther.getPkFkEquipo())
 && (this.getPkFkTorneo()==castOther.getPkFkTorneo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkFkPasaporteXfifa();
         result = 37 * result + this.getPkFkEquipo();
         result = 37 * result + this.getPkFkTorneo();
         return result;
   }   


}


