package com.myhistory.datos.tablas;
// Generated 16/06/2014 01:29:29 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerfilEstadistico generated by hbm2java
 */
@Entity
@Table(name="PERFIL_ESTADISTICO"
    ,schema="dbo"
    ,catalog="MY_HISTORY"
)
public class PerfilEstadistico  implements java.io.Serializable {


     private PerfilEstadisticoId id;
     private Equipo equipo;
     private Jugador jugador;
     private Torneo torneo;
     private int juegosGanados;
     private int juegosPerdidos;
     private int juegosEmpatados;
     private int goles;
     private int tirosMarco;
     private int asistencias;
     private int recuperaciones;
     private int tarjetasAmarillas;
     private int tarjetasRojas;
     private int penalesDetenidos;
     private int penalesCometidos;
     private int ramatesSalvados;
     private double notaXfifa;
     private int ano;

    public PerfilEstadistico() {
    }

    public PerfilEstadistico(PerfilEstadisticoId id, Equipo equipo, Jugador jugador, Torneo torneo, int juegosGanados, int juegosPerdidos, int juegosEmpatados, int goles, int tirosMarco, int asistencias, int recuperaciones, int tarjetasAmarillas, int tarjetasRojas, int penalesDetenidos, int penalesCometidos, int ramatesSalvados, double notaXfifa, int ano) {
       this.id = id;
       this.equipo = equipo;
       this.jugador = jugador;
       this.torneo = torneo;
       this.juegosGanados = juegosGanados;
       this.juegosPerdidos = juegosPerdidos;
       this.juegosEmpatados = juegosEmpatados;
       this.goles = goles;
       this.tirosMarco = tirosMarco;
       this.asistencias = asistencias;
       this.recuperaciones = recuperaciones;
       this.tarjetasAmarillas = tarjetasAmarillas;
       this.tarjetasRojas = tarjetasRojas;
       this.penalesDetenidos = penalesDetenidos;
       this.penalesCometidos = penalesCometidos;
       this.ramatesSalvados = ramatesSalvados;
       this.notaXfifa = notaXfifa;
       this.ano = ano;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkFkPasaporteXfifa", column=@Column(name="PK_FK_Pasaporte_XFIFA", nullable=false) ), 
        @AttributeOverride(name="pkFkEquipo", column=@Column(name="PK_FK_Equipo", nullable=false) ), 
        @AttributeOverride(name="pkFkTorneo", column=@Column(name="PK_FK_Torneo", nullable=false) ) } )
    public PerfilEstadisticoId getId() {
        return this.id;
    }
    
    public void setId(PerfilEstadisticoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_FK_Equipo", nullable=false, insertable=false, updatable=false)
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_FK_Pasaporte_XFIFA", nullable=false, insertable=false, updatable=false)
    public Jugador getJugador() {
        return this.jugador;
    }
    
    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_FK_Torneo", nullable=false, insertable=false, updatable=false)
    public Torneo getTorneo() {
        return this.torneo;
    }
    
    public void setTorneo(Torneo torneo) {
        this.torneo = torneo;
    }

    
    @Column(name="Juegos_Ganados", nullable=false)
    public int getJuegosGanados() {
        return this.juegosGanados;
    }
    
    public void setJuegosGanados(int juegosGanados) {
        this.juegosGanados = juegosGanados;
    }

    
    @Column(name="Juegos_Perdidos", nullable=false)
    public int getJuegosPerdidos() {
        return this.juegosPerdidos;
    }
    
    public void setJuegosPerdidos(int juegosPerdidos) {
        this.juegosPerdidos = juegosPerdidos;
    }

    
    @Column(name="Juegos_Empatados", nullable=false)
    public int getJuegosEmpatados() {
        return this.juegosEmpatados;
    }
    
    public void setJuegosEmpatados(int juegosEmpatados) {
        this.juegosEmpatados = juegosEmpatados;
    }

    
    @Column(name="Goles", nullable=false)
    public int getGoles() {
        return this.goles;
    }
    
    public void setGoles(int goles) {
        this.goles = goles;
    }

    
    @Column(name="Tiros_Marco", nullable=false)
    public int getTirosMarco() {
        return this.tirosMarco;
    }
    
    public void setTirosMarco(int tirosMarco) {
        this.tirosMarco = tirosMarco;
    }

    
    @Column(name="Asistencias", nullable=false)
    public int getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(int asistencias) {
        this.asistencias = asistencias;
    }

    
    @Column(name="Recuperaciones", nullable=false)
    public int getRecuperaciones() {
        return this.recuperaciones;
    }
    
    public void setRecuperaciones(int recuperaciones) {
        this.recuperaciones = recuperaciones;
    }

    
    @Column(name="Tarjetas_Amarillas", nullable=false)
    public int getTarjetasAmarillas() {
        return this.tarjetasAmarillas;
    }
    
    public void setTarjetasAmarillas(int tarjetasAmarillas) {
        this.tarjetasAmarillas = tarjetasAmarillas;
    }

    
    @Column(name="Tarjetas_Rojas", nullable=false)
    public int getTarjetasRojas() {
        return this.tarjetasRojas;
    }
    
    public void setTarjetasRojas(int tarjetasRojas) {
        this.tarjetasRojas = tarjetasRojas;
    }

    
    @Column(name="Penales_Detenidos", nullable=false)
    public int getPenalesDetenidos() {
        return this.penalesDetenidos;
    }
    
    public void setPenalesDetenidos(int penalesDetenidos) {
        this.penalesDetenidos = penalesDetenidos;
    }

    
    @Column(name="Penales_Cometidos", nullable=false)
    public int getPenalesCometidos() {
        return this.penalesCometidos;
    }
    
    public void setPenalesCometidos(int penalesCometidos) {
        this.penalesCometidos = penalesCometidos;
    }

    
    @Column(name="Ramates_Salvados", nullable=false)
    public int getRamatesSalvados() {
        return this.ramatesSalvados;
    }
    
    public void setRamatesSalvados(int ramatesSalvados) {
        this.ramatesSalvados = ramatesSalvados;
    }

    
    @Column(name="Nota_XFIFA", nullable=false, precision=53, scale=0)
    public double getNotaXfifa() {
        return this.notaXfifa;
    }
    
    public void setNotaXfifa(double notaXfifa) {
        this.notaXfifa = notaXfifa;
    }

    
    @Column(name="Ano", nullable=false)
    public int getAno() {
        return this.ano;
    }
    
    public void setAno(int ano) {
        this.ano = ano;
    }




}


