package com.myhistory.datos.tablas;
// Generated 16/06/2014 01:29:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Torneo generated by hbm2java
 */
@Entity
@Table(name="TORNEO"
    ,schema="dbo"
    ,catalog="MY_HISTORY"
)
public class Torneo  implements java.io.Serializable {


     private int pkTorneo;
     private String nombre;
     private String nombreSede;
     private int cantidadJugadores;
     private boolean deSeleccion;
     private boolean deCopa;
     private Set<PerfilEstadistico> perfilEstadisticos = new HashSet<PerfilEstadistico>(0);

    public Torneo() {
    }

	
    public Torneo(int pkTorneo, String nombre, String nombreSede, int cantidadJugadores, boolean deSeleccion, boolean deCopa) {
        this.pkTorneo = pkTorneo;
        this.nombre = nombre;
        this.nombreSede = nombreSede;
        this.cantidadJugadores = cantidadJugadores;
        this.deSeleccion = deSeleccion;
        this.deCopa = deCopa;
    }
    public Torneo(int pkTorneo, String nombre, String nombreSede, int cantidadJugadores, boolean deSeleccion, boolean deCopa, Set<PerfilEstadistico> perfilEstadisticos) {
       this.pkTorneo = pkTorneo;
       this.nombre = nombre;
       this.nombreSede = nombreSede;
       this.cantidadJugadores = cantidadJugadores;
       this.deSeleccion = deSeleccion;
       this.deCopa = deCopa;
       this.perfilEstadisticos = perfilEstadisticos;
    }
   
     @Id 

    
    @Column(name="PK_Torneo", unique=true, nullable=false)
    public int getPkTorneo() {
        return this.pkTorneo;
    }
    
    public void setPkTorneo(int pkTorneo) {
        this.pkTorneo = pkTorneo;
    }

    
    @Column(name="Nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Nombre_Sede", nullable=false, length=30)
    public String getNombreSede() {
        return this.nombreSede;
    }
    
    public void setNombreSede(String nombreSede) {
        this.nombreSede = nombreSede;
    }

    
    @Column(name="Cantidad_Jugadores", nullable=false)
    public int getCantidadJugadores() {
        return this.cantidadJugadores;
    }
    
    public void setCantidadJugadores(int cantidadJugadores) {
        this.cantidadJugadores = cantidadJugadores;
    }

    
    @Column(name="De_Seleccion", nullable=false)
    public boolean isDeSeleccion() {
        return this.deSeleccion;
    }
    
    public void setDeSeleccion(boolean deSeleccion) {
        this.deSeleccion = deSeleccion;
    }

    
    @Column(name="De_Copa", nullable=false)
    public boolean isDeCopa() {
        return this.deCopa;
    }
    
    public void setDeCopa(boolean deCopa) {
        this.deCopa = deCopa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="torneo")
    public Set<PerfilEstadistico> getPerfilEstadisticos() {
        return this.perfilEstadisticos;
    }
    
    public void setPerfilEstadisticos(Set<PerfilEstadistico> perfilEstadisticos) {
        this.perfilEstadisticos = perfilEstadisticos;
    }




}


