//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoccer.Datos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NARRADOR
    {
        public int PK_FK_Narrador { get; set; }
        public int Genero { get; set; }
        public string Foto { get; set; }
        public int Anos_Experiencia { get; set; }
        public string Descripcion { get; set; }
    }
}
